# ADR-022: remote state in Azure Storage, not local state -- local state has no place to live safely
# in a GitHub Actions runner (ephemeral) and would otherwise need to be committed to the repo, which
# risks leaking resource IDs/secrets that end up in state.
#
# This is a *partial* backend configuration deliberately -- backend blocks cannot reference
# variables, and the storage account name is globally unique (generated by
# infra/scripts/bootstrap-terraform-state.sh, run once before the first `terraform init`). Supply the
# concrete values via `-backend-config`:
#
#   terraform init \
#     -backend-config="resource_group_name=<from bootstrap script output>" \
#     -backend-config="storage_account_name=<from bootstrap script output>" \
#     -backend-config="container_name=tfstate" \
#     -backend-config="key=helix.tfstate"
#
# CI does this automatically (see .github/workflows/terraform-plan.yml /
# terraform-apply.yml) using repository variables set once after bootstrapping.

terraform {
  backend "azurerm" {}
}
